# Generated by Django 6.0.4 on 2026-07-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=2),
        ),
    ]
