# Generated by Django 6.0.4 on 2026-07-31 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_price_alter_restaurant_delivery_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default pricing settings', max_length=100, verbose_name='Setting Name')),
                ('base_fee', models.IntegerField(default=15000, help_text='Base delivery fee (IRR)', verbose_name='Base Fee')),
                ('per_km_rate', models.IntegerField(default=5000, help_text='Delivery fee per kilometer (IRR)', verbose_name='Rate per Kilometer')),
                ('lunch_peak_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)], verbose_name='Lunch Peak Multiplier (12:00 to 15:30)')),
                ('dinner_peak_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)], verbose_name='Dinner Peak Multiplier (19:00 to 22:30)')),
                ('condition_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Condition multiplier for special conditions like rain, snow, or heavy traffic (1.0 = normal)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)], verbose_name='Special Conditions/Weather Coefficient')),
                ('min_fee', models.IntegerField(default=20000, help_text='Minimum delivery fee (IRR)', verbose_name='Minimum Delivery Fee')),
                ('max_fee', models.IntegerField(default=150000, help_text='Maximum delivery fee (IRR)', verbose_name='Maximum Delivery Fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
    ]
