# Generated by Django 6.0.4 on 2026-08-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_courier_user_order_user_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the item at the time of purchase', max_length=150)),
                ('price', models.DecimalField(decimal_places=0, help_text='Unit price at the time of purchase', max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.order')),
            ],
        ),
    ]
