# Generated by Django 6.0.4 on 2026-04-20 12:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, help_text='The full service area boundary (can include multiple polygons)', srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(geography=True, help_text='Draw the delivery zone boundary on the map', srid=4326)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('min_order', models.DecimalField(decimal_places=2, default=1000, max_digits=8)),
                ('estimated_time', models.IntegerField(default=30, help_text='Minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'name'],
            },
        ),
    ]
