# Generated by Django 6.0.4 on 2026-07-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
    ]
